services:
  ipfs:
    image: ipfs/kubo:latest
    restart: unless-stopped
    ports:
      - "5001:5001"
    command: daemon --migrate=true
    volumes:
      - ipfs-data:/data/ipfs

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: graph
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: graph
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  graph-node:
    image: graphprotocol/graph-node:latest
    restart: unless-stopped
    depends_on:
      - ipfs
      - postgres
    ports:
      - "8000:8000"   # GraphQL
      - "8020:8020"   # Admin
      - "8030:8030"   # Indexing status
      - "8040:8040"   # Metrics
    environment:
      # entrypoint needs these split vars for its wait-for checks
      postgres_host: postgres
      postgres_port: 5432
      postgres_user: graph
      postgres_pass: letmein
      postgres_db:   graph

      # the runtime uses this URL
      postgres_url: "postgresql://graph:letmein@postgres:5432/graph"

      ipfs: "ipfs:5001"
      ethereum: "doma-testnet:https://rpc-testnet.doma.xyz"
      RUST_LOG: info
      RUST_BACKTRACE: full

volumes:
  ipfs-data:
  pg-data:
